# Generated by Django 4.2.6 on 2024-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
